# Generated by Django 3.2.9 on 2022-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
